version: '3.4'

services:
  monitoringnotificationsystem.notificationcenter:
    image: ${DOCKER_REGISTRY-}monitoringnotificationsystemnotificationcenter
    build:
      context: .
      dockerfile: MonitoringNotificationSystem.NotificationCenter/Dockerfile
    depends_on:
      - monitoringnotificationsystem.mongo
      - monitoringnotificationsystem.rabbitmq

  monitoringnotificationsystem.server:
    image: ${DOCKER_REGISTRY-}monitoringnotificationsystemserver
    build:
      context: .
      dockerfile: MonitoringNotificationSystem.Server/Dockerfile
    depends_on:
      - monitoringnotificationsystem.rabbitmq


  monitoringnotificationsystem.webapp:
    image: ${DOCKER_REGISTRY-}monitoringnotificationsystemwebapp
    build:
      context: .
      dockerfile: MonitoringNotificationSystem.Webapp/Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - monitoringnotificationsystem.notificationcenter

  monitoringnotificationsystem.mongo:
     image: docker.io/library/mongo:latest
     ports:
     - "27017:27017"

  monitoringnotificationsystem.rabbitmq:
    image: docker.io/library/rabbitmq:3-management
    ports:
      - "5672:5672"
      - "8080:15672"

